### PR TITLE
Added code for magic permutation

### PR DESCRIPTION
**Pull request by dsasaank-369**

### CODE REVIEW

**Comment by dsasaank-369** [comment]
Please accept this under hactober-accepted

**Comment by saptarshisarkar20** [comment]
No codes here

**Comment by dsasaank-369** [comment]
> No codes here
It is present in codechef folder, name of the folder 2 ndOct_dsasaank-369.py

**Comment by dsasaank-369** [comment]
It's not reflected in Hactober, it says that the project not participating

**Pull request merged**
